### ISSUE TITLE
Fix Google Map

### ISSUE THREAD

**Issue by FWirtz** [HackHPI/hackhpi.github.io#15]
The map is currently non-interactive and mostly generated from images.
This works.
Is it desired though? Or do we rather want to have an interactive version?

**Comment by FWirtz** [comment]
Changing it seems like a lot of work for little improvement, could also ignore this IMO.
What do you think @jak-ing @jonashering @ma-ro?

**Comment by jonashering** [comment]
Okay, now I see... 😄  Agree with @jak-ing.

**Comment by FWirtz** [comment]
sounds good!

**Comment by jonashering** [comment]
Map is non-interactive due to an overlying div (`<div class="location-map-overlay"></div>`).

Map must not be interactive to avoid behaviour like this:
![bildschirmfoto 2018-02-01 um 23 51 33](https://user-images.githubusercontent.com/15236859/35736529-a9b060e4-0828-11e8-85b4-4285d5bede6d.png)

@jak-ing proposed to add a link once the map is clicked. That way, users won't be confused by the not working controls.
